services:
    db:
        image: postgres:14-alpine
        restart: always
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: example
            POSTGRES_DB: petpro
        volumes:
            - db-data:/var/lib/postgresql/data
        ports:
            - '5433:5432'

    backend:
        build:
            context: ./backend
            dockerfile: Dockerfile
        depends_on:
            - db
        environment:
            PORT: 3000
        ports:
            - '3000:3000'
        volumes:
            - ./backend:/usr/src/app

    frontend:
        build:
            context: ./frontend
            dockerfile: Dockerfile
        depends_on:
            - backend
        ports:
            - '5173:5173'
        volumes:
            - ./frontend:/app

volumes:
    db-data:
